CREATE TABLE event
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    type       VARCHAR(255),
    status     VARCHAR(255),
    start_time TIMESTAMP WITHOUT TIME ZONE,
    end_time   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_event PRIMARY KEY (id)
);

CREATE TABLE seat_types
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255),
    price    DECIMAL,
    event_id BIGINT,
    CONSTRAINT pk_seat_types PRIMARY KEY (id)
);

CREATE TABLE seats
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    row_number   VARCHAR(255),
    seat_number  VARCHAR(255),
    status       VARCHAR(255),
    seat_type_id BIGINT,
    event_id     BIGINT,
    CONSTRAINT pk_seats PRIMARY KEY (id)
);

ALTER TABLE seats
    ADD CONSTRAINT FK_SEATS_ON_EVENT FOREIGN KEY (event_id) REFERENCES event (id);

ALTER TABLE seats
    ADD CONSTRAINT FK_SEATS_ON_SEAT_TYPE FOREIGN KEY (seat_type_id) REFERENCES seat_types (id);

ALTER TABLE seat_types
    ADD CONSTRAINT FK_SEAT_TYPES_ON_EVENT FOREIGN KEY (event_id) REFERENCES event (id);